### ISSUE TITLE
When shadow copying is enabled, the runner does not set the Environment.CurrentDirectory correctly

### ISSUE THREAD

**Issue by chrischu** [machine/machine.specifications.runner.resharper#39]
When activating shadow copying of test assemblies in ReSharper, the MSpec runner seems to incorrectly set the Environment.CurrentDirectory.

Interestingly enough the AppDomain.CurrentDomain.BaseDirectory points to the original build directory (e.g. C:\Solution\Project\bin\Debug), but Environment.CurrentDirectory points to the temporary directory with the shadow-copied assemblies.

This leads to test errors when using relative paths in tests.

**Comment by bluerobotch** [comment]
As a work around, you can create an AssemblyContext that sets the CurrentDirectory as follows: [FixCurrentDirectoryAssemblyContext.cs](https://gist.github.com/bluerobotch/aa267814f730c7756a01b758165009da)

**Comment by robertcoltheart** [comment]
FWIW, the xunit runner does the same thing, ie sets the `Environment.CurrentDirectory`. @ivanz How should we handle this?

**Comment by ivanz** [comment]
I thought this is already the case? See here: https://github.com/machine/machine.vstestadapter/blob/master/Source/Machine.VSTestAdapter/Execution/AssemblyLocationAwareRunListener.cs and here: https://github.com/machine/machine.vstestadapter/blob/129f1d610c8aca9234c3973fbfc2991029b6b513/Source/Machine.VSTestAdapter/Execution/TestExecutor.cs#L45

**Comment by robertcoltheart** [comment]
Ok, so perhaps I don't need to set `Environment.CurrentDirectory` in the R# runner. Will test.

**Comment by ivanz** [comment]
I suspect maybe the mspec test adapter is not anticipating that something up the stack has already shadowed copied the assemblies? If ReSharper is shadow copying then I suspect maybe the `loadedAssebmly.Location` in the code is pointing to the shadow-copy directory thus the current directory gets changed to the wrong place?

I do remember having to set the current directory, because it wasn't set properly by `dotnet test`/VS2017 at the time. Maybe it was the case that it set it to the current directory the command was triggered or the solution directory in the case of VS2017 - can't recall. I expect tests will fail if you comment out the `AssemblyLocationAwareRunListener` - if not maybe we are fine to drop it...

Keep in mind that for full .NET Framework the test adapter itself is shadow copying during execution and test discovery (see `IsolatedAppDomainExecutionScope` in the adapter). I can't recall the exact specifics at the moment, but I do remember that shadow copying was required in order to avoid locking the .dlls when using the built-in Visual Studio IDE 2015 GUI runner (Test Window) . If this is no longer needed in VS2017 for both new-style and old-style .csproj targeting .Net Framework and tests being ran via the VS2017 built-in test window runner - we can drop it and drop VS2015 support.

**Comment by drauch** [comment]
Running tests without shadow copying is still preventing you from building the solution in VS2017.

**Comment by ivanz** [comment]
@drauch Is this when:

1. Using ReSharper for new-style csproj
2. Using ReSharper for old-style csporj
3. Using VS GUI runner for new-style csproj
4. Using VS GUI runner for old-style csproj
5. .NET Core target
6. .NET Framework target

:)

**Comment by drauch** [comment]
We're using a combination of (1) and (6)
