### ISSUE TITLE
VS 2017 new csproj format support

### ISSUE THREAD

**Issue by MrHypnos** [machine/machine.specifications.runner.resharper#71]
Hello there,

Is the new csproj format supported in VS 2017 ?

I'm having trouble running tests in VS 2017 with the latest version of VS 2017, Reshaper and MS reshaper runner plugin against a **new** csproj project.

I'm unable to do the usual "Right click on the csproj > Run tests" or "Right click on a file > Run tests" in Visual Studio 2017.

The only work around so far, it's to open the file, then let it load a second, then the option to run the test on that file only becomes available.

Do we need to do anything in the csproj to help the mspec runner to discover mspec tests ?

Also, it all works fine with using the mspec console runner against the same assembly.

Thanks !

**Comment by robertcoltheart** [comment]
Pretty sure you'll need to build your project first, but I'll investigate and see if there's something else missing. Sorry for the delay, I was on vacation.

**Comment by robertcoltheart** [comment]
Ok, I've replicated this and this is an issue with R# itself. Once you build the project, the right-click option to run tests becomes available for that project. As a workaround, you can use the test explorer to run all tests from the solution, or use the menu option "Resharper->Unit tests->Run all tests from solution".

@citizenmatt is this a bug or by design?

**Comment by citizenmatt** [comment]
This might actually be a question of timing - we only show the menu item when we've had a chance to discover tests. I can't remember right now when the source based discovery happens after project opening, but there can be a delay as we scan files. I think we also cache discovered tests, so there can also be a delay (but hopefully a shorter one) when reopening a solution that's already had discovery complete. It would be interesting to see what happens if you just leave the project for a minute or two so we get chance to scan.

Building will force the issue, though, as we do a different phase of test discovery here - by asking the `dotnet.exe` testing infrastructure what tests it knows about. Once we have tests from here, we can show the context menu.

But my knowledge here is a bit hazy lately. I'll follow up with the dev team.

**Comment by robertcoltheart** [comment]
Thanks @citizenmatt, I still think this is a potential bug in R#, as I can reliably produce the behavior by doing the below:

1. Open test solution and run "Clean Solution", make sure all file editors are closed
2. Close VS
3. Re-open VS and open the test solution
4. Waited for 5+ mins and **did not see** the "Run unit tests" option on the project right-click menu
5. Open a file, now the option appears on the right-menu, and all tests are discovered.

Happy to attach a sample solution if that helps.
