### ISSUE TITLE
Resharper 2017 shows no mspec related naming style options

### ISSUE THREAD

**Issue by Hyp3rion** [machine/machine.specifications.runner.resharper#84]
In Resharper 2017.3 I see no mspec related "afftected entities" under Options-> Code Editing -> C# ->Naming Style -> Advanced Settings

I tried reinstalling the Resharper Runner Plugin.

What am I missing?

![2018-04-09 10_18_21-edit extended naming rule](https://user-images.githubusercontent.com/722260/38497001-d7a5407c-3bff-11e8-8f98-5178110e60d6.png)

**Comment by Hyp3rion** [comment]
In addition the Unit Test Submenu from Resharper only allows me to run tests from a session or from the solution. Why not from current context?
![2018-04-10 10_31_51-](https://user-images.githubusercontent.com/722260/38545555-9651237e-3caa-11e8-88a5-7e285b7bde1c.png)

**Comment by robertcoltheart** [comment]
Hi @Hyp3rion, mspec naming conventions are not supported by the plugin at this time. For (2), I'm guessing you're using the new csproj (either net.core or netstandard)? In which case, you need to build the project first before this menu option becomes available. This is a VS requirement due to the way .net core runs tests, nothing to do with R#.
